### ISSUE TITLE
使用autoxjs打包安卓运行一直显示软件加载中

### ISSUE THREAD

**Issue by msdog** [xxxxue/autojs_web#3]
直接运行可以,但是打包后就运行一直显示软件加载中

**Comment by xxxxue** [comment]
> 直接运行可以,但是打包后就运行一直显示软件加载中


一会中午，我去看看。

**Comment by xxxxue** [comment]
解决了. 
aj 在打包的时候会将后缀为 js 的文件都加密. 
所以浏览器就识别不出来js.
把 浏览器要加载的 js 文件后缀改为 jsx 就可以跳过 aj 的打包的加密了.


具体的修改在这里 https://github.com/xxxxue/autojs_web/commit/400b89d2185fbe4065c679e738ddce8e16a3a73d

**Comment by msdog** [comment]
感谢
